version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    container_name: gcode-db
    volumes:
      - gcode-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: gcode
      MYSQL_DATABASE: galaxieonCode
    networks:
      - gcode-network
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: gcode-server:dev
    container_name: gcode-dev-server
    depends_on:
      - mariadb
    environment:
      PORT: "80"
      DB_HOST: mariadb
      DB_USER: root
      DB_PASS: gcode
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app/
    networks:
      - gcode-network

  nginx:
    build:
      context: nginx
      dockerfile: ./Dockerfile
    image: gcode-nginx:dev
    container_name: gcode-nginx
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - gcode-network

volumes:
  gcode-data:
    name: gcode-data

networks:
  gcode-network:
    name: gcode-network
    driver: bridge
